server:
  port: 8081
  servlet:
    context-path: /TeachingAffairs
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teachingaffairs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ZXZX78078
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true